version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  s3:
    #accesskey: awsaccesskey
    #secretkey: awssecretkey
    #region: eu-west-1
    #bucket: bucketname
    encrypt: true
    secure: true
    v4auth: true
    chunksize: 5242880
    #rootdirectory: /s3/object/name/prefix
auth:
  htpasswd:
    realm: basic-realm
    path: /config/registry/htpasswd
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
